//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GanttChartWebLibrary_NET_SQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Predecessors = new HashSet<Predecessor>();
            this.Successors = new HashSet<Predecessor>();
        }
    
        public int ID { get; set; }
        public int Index { get; set; }
        public string Name { get; set; }
        public int Indentation { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime Finish { get; set; }
        public System.DateTime Completion { get; set; }
        public bool IsMilestone { get; set; }
        public string Assignments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predecessor> Predecessors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predecessor> Successors { get; set; }
    }
}
